spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_dev_db?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 10000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG

app:
  featureFlags:
    enableSampleData: true
    sendEmails: false
  cors:
    allowedOrigins:
      - http://localhost:4200
