spring:
  datasource:
    url: jdbc:mysql://uat-db:3306/student_uat_db?useSSL=true&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 3
      idle-timeout: 30000
      connection-timeout: 25000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

logging:
  level:
    root: INFO
    org.springframework: INFO

app:
  featureFlags:
    enableSampleData: false
    sendEmails: true
  cors:
    allowedOrigins:
      - https://uat.your-domain.com
