server:
  port: 8888

spring:
  application:
    name: democonfig

  cloud:
    config:
      server:
        composite:
          - type: git
            uri: https://github.com/susheel2405/configserver.git
            default-label: main
            clone-on-start: true
            search-paths: .
          - type: vault
            backend: secret
            default-key: student-service

    vault:
      uri: http://127.0.0.1:8200
      token: ${VAULT_TOKEN:root}
      authentication: TOKEN

management:
  endpoints:
    web:
      exposure:
        include: health,info,env
  endpoint:
    health:
      show-details: always
